new_request = {
    "express_resumes":{
        "size":1,
        "from":0
    },
    "size":20,
    "recruiter_db_access_contexts":[
        "rexmonster"
    ],
    "from":0,
    "sub_channel_id":1,
    "recruiter_company_name":"Emmess Technologies Private Limited",
    "subuid":853349,
    "service_filter":{

    },
    "channel_id":1,
    "corp_id":536610,
    "site_context":"rexmonster",
    "filters":{
        "experience":{
            "min_exp":5.0,
            "max_exp":8.0
        },
        "location":{
            "current_locations":[
                "Bengaluru / Bangalore"
            ],
            "current_preferred_location_cond":"AND"
        },
        "company":{
            "any_scope":"c",
            "exclude_scope":"c",
            "designations_scope":"c",
            "notice_period":30,
            "currency":"INR",
            "max_ctc":1500000,
            "include_profiles_with_no_ctc":1,
            "include_profiles_with_no_notice_period":1
        },
        "education":{
            "yop_from":0,
            "yop_to":0,
            "highest_second_cond":"AND"
        },
        "additional":{
            "show_active_created":"active",
            "active_created_days":180
        }
    },
    "strict":True,
    "refine_search":{
        "sort_by":"relevance"
    },
    "queries":{
        "search_within":"contents",
        "lenient":0,
        "search_scope_id":1,
        "boolean":"\\""Full stack developer\\"" AND (\\""spring\\"" OR \\""spring boot\\"") AND \\""react\\"""
    },
    "forUI":{
        "locations":{
            "loc":{
                "InTopCities":[
                    "Bengaluru / Bangalore"
                ]
            }
        }
    },
    "uniq_id":"84511322109922693608",
    "currency":"INR",
    "maskingToBeEnabled":True
}