dict_obj =  {  "resume_text":"Date of Birth \n\n10 February 1987 \n\nSulaiman Bin Abdul Rahman \n\nS8702981F \n\nMale "
                             "\n\n297D Choa "
                             "Chu Kang Avenue 2, #05-98, 684297 \n\nContact No. \n\n+65 6762 0694 (Home) +65 9658 "
                             "0179 (Mobile) \n\nE-mail Address \n\n000sulaiman000@gmail.com \n\nCURRICULUM   VITAE   "
                             "\n\nPERSONAL PARTICULARS \n\nName \n\n \n\nNRIC No. \n\nSex \n\n \n\nAddress "
                             "\n\nWebsite \n\nNationality \n\nRace \n\n \n\nEDUCATION \n\n \n\n \n\n \n\n \n\n \n\n "
                             "\n\n \n\n \n\n \n\n: \n\n: \n\n: \n\n: \n\n: \n\n: \n\n: \n\n: \n\n: \n\n: "
                             "\n\nhttp://000sulaiman000.weebly.com \n\nSingaporean \n\nMalay \n\nWORK EXPERIENCE "
                             "\n\nNanyang Technological University, Singapore, \n(Aug 2009 – July 2016) \n\nFreelance "
                             "3D Human Scan Clean-up Artist with \nJiffit Pte Ltd. (Part-time, July 2015 – Jan 2016) "
                             "\n\n\uf0a7  Bachelor of Fine Arts Majoring in Digital \n\nAnimation \n\nNanyang "
                             "Polytechnic, Singapore,  \n(Jun 2004 – Mar 2007) \n\n\uf0a7  Diploma in Digital "
                             "Entertainment \n\nTechnology \n\n\uf0a7  Cumulative Grade Point Average of 3.65 \n\n "
                             "\nUnity Secondary School, Singapore,  \n(Jan 2000 – Dec 2003) \n\n\uf0a7 \n\n‘O’ Levels "
                             "\n\n \n\n \n\nBukit Panjang Primary School, Singapore, \n(Jan 1994 – Dec 1999) "
                             "\n\n\uf0a7  Primary School Leaving Examination \n\n(PSLE) \n\n \n\n \n\nTECHNICAL "
                             "SKILLS \n\nDigital Media Skills: \n\nTraditional Media Skills: \n\nJob  scope:  "
                             "Clean-up,  Sculpt  details,  Patch  up \ntextures,  Polish,  UV  Mapping  &  Decimating "
                             " 3D \ngenerated  meshes  from  Agisoft  Photoscan  using \nZBrush, for the purpose of "
                             "3D printing into desktop \nfigurines. \n\n \nSTUDENT INTERNSHIP DURING DIPLOMA "
                             "\n\nA*STAR  Singapore  Institute  of  Manufacturing \nTechnology, (Sept – Dec 2006) "
                             "\n\n\uf0b7  Worked  on  creating  a  Virtual  Simulation \nof  Robot  using  UNREAL  "
                             "Tournament \n2004 Game Engine Scripting.  \n\n\uf0b7  Used  UNREAL  Tournament  2004  "
                             "Level \nEditor  to  virtually  replicate  SIM  Tech  Lab \nEnvironment.  \n\n\uf0b7  "
                             "Modelled 3D models of 3 Wheeled Robot \nand  Robotic  Arms  in  Alias  Maya  7.0  to "
                             "\nbe used in the Game Engine. \n\nMaya, 3ds Max, ZBrush, Keyshot, Photoshop, Premiere, "
                             "After Effects, Unreal Engine 4, Quixel Suite. \n\nPencil/Pen/Charcoal/Pastel Drawing, "
                             "Basic Concept Sketching \n\nComputer Technology Skills: \n\nWindows OS / Mac OS usage, "
                             "Microsoft Office, Basic Computer Hardware "
                             "\nMaintenance/Assembly/Repair/Troubleshooting, Basic Networking Troubleshooting. "
                             "\n\nNTU SOLO FINAL YEAR PROJECT \n\n“DISTURBANCES” – Realtime interactive VR "
                             "horror/sci-fi interior demo made with Unreal Engine 4, \n3Ds Max, Photoshop, "
                             "Quixel Suite 2, Marvelous Designer. Oculus DK2 and Leap Motion Controller \nwere used "
                             "as seen here: http://blogs.ntu.edu.sg/adm-portfolio/project/disturbances/ \n\n\\x0c"}
str_obj = dict_obj['resume_text']

new_str = ' '.join(str_obj.replace('\n', ' ').split())
print(f"old string length = {len(str_obj)} \nnew string length = {len(new_str)}")
print(f"old string = {str_obj} \nnew string = {new_str}")